# fly.toml app configuration file generated for codezilla-backend-silent-grass-8737 on 2024-12-06T03:18:13+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codezilla-backend-silent-grass-8737'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
